### ISSUE TITLE
typed resolvers

### ISSUE THREAD

**Issue by jardakotesovec** [dangcuuson/graphql-schema-typescript#6]
Hi, this is great project, exactly what I was looking for!

As you say in readme, resolver result is any at this moment and can be explicitly defined in resolvers. I am wondering what was the reason to leave results as any? Are you considering to have option that would also type the results of resolvers?

**Comment by dangcuuson** [comment]
Hi **jardakotesovec**, I'm glad that you like this project :smile: 

The reason I leave the resolve result default to `any` is because sometimes, the developer may not want to fully resolve the object, but leave some fields to be resolved in a lazy way due to expensive code if resolved directly. 

For example, with this schema:
```graphql
schema {
  query: RootQuery
}

type RootQuery {
  user: User
}

type User {
  username: String!
  email: String!
  # assuming this could be expensive due to additional database query
  history: [UserHistory!]
}

type UserHistory{
 # etc.
}
```

Then in the `RootQueryToUserResolver` function, they may want to resolve `username` and `email` only, and either wrap `history` in another resolve function, or completely ignore it and let `UserToHistoryResolver` to do its job. They may also want to return additional information to help `UserToHistoryResolver` resolve its type as well(although I can't think of a reason why).

However, now when you bring this up, I think I was overthinking back then. :smile: 
I believe I could make the lib to be a little "smart" by set the default resolve result of `RootQueryToUserResolver` to `User` instead of `any`, and developer can still overwrite them if they don't like it.

The same thinking process was applied for `TParent` as well. 

A new option to have a smarter default type will be implemented soon!

**Comment by dangcuuson** [comment]
Btw if you have any idea or suggestion, please feel free to discuss them here.

**Comment by dangcuuson** [comment]
I have added some options to make default TParent and TContext type not `any`

You can check new version (`1.2.2`) with these options:  `smartTParent` `smartTResult` and `asyncResult`.

Happy coding :smile:

**Comment by jardakotesovec** [comment]
@dangcuuson Awesome! Will try it out next week. Closing this, I will open another issue if I have some particular issue with these updates :-). Thanks!

**Comment by AndreiEzhov** [comment]
I'll try to explain myself better.

Let's say I'm using RootQueryToUserResolver, and I'm fetching from an API that returns some of the data I need, let's call the type UserModel. I get the error 
>Type 'RootQueryToUserResolver<unknown, UserModel | null>' is not assignable to type 'RootQueryToUserResolver<unknown, User | null>'

How would I write a class that implements RootQueryTypeResolver but overrides RootQueryToUserResolver so TResult is UserModel?
